# <center>Introduction to Numpy</center>
![](http://m.memegen.com/o6i6hi.jpg)

![](https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei)


# What is Numpy?
---

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

# Installation
---

![](https://i.imgflip.com/21yk3f.jpg)

- **Mac** and **Linux** users can install NumPy via pip command:
    ```
    pip install numpy
    ```

- **Windows** does not have any package manager analogous to that in linux or mac. Please download the pre-built windows installer for NumPy from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) (according to your system configuration and Python version). And then install the packages manually.


Once you are done, just type this in python interpreter:
```python
import numpy as np
```

If you are still experiencing some issues, then Stack Overflow is your friend!

If no errors appear,congo! You have successfully installed NumPy. 
Lets move ahead...


In [107]:
import numpy

## Arrays in NumPy
---
NumPy’s main object is the homogeneous multidimensional array.
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy dimensions are called *axes*. The number of axes is *rank*.
- NumPy’s array class is called **ndarray**. It is also known by the alias **array**. 

For example:
```python
[[ 1, 2, 3],
 [ 4, 2, 5]]
```  
This array has:
- rank = 2 (as it is 2-dimensional or it has 2 axes)
- first dimension(axis) length = 2, second dimension has length = 3.
- overall shape can be expressed as: (2, 3)

In [108]:
import numpy as np

In [109]:
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])

In [110]:
arr

array([[1, 2, 3],
       [4, 2, 5]])

In [111]:
# type of arr
type(arr)

numpy.ndarray

In [112]:
# shape of arr
arr.shape

(2, 3)

In [113]:
# type of elements inside array
arr.dtype

dtype('int64')

![](https://memegenerator.net/img/instances/400x/74259368.jpg)

## Array creation
---
There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python **list** or **tuple** using the **array** function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [114]:
mylist = [[1,2,3,4],
          [5,6,7,8]]

In [120]:
myarr = np.array(mylist, dtype='complex')

In [121]:
myarr

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [117]:
myarr.dtype

dtype('int64')

- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with **initial placeholder content**. These minimize the necessity of growing arrays, an expensive operation. **For example:** np.zeros, np.ones, np.full, np.empty, etc.

In [122]:
# create an array of size 3x4 filled with 0s
c = np.zeros((3,4))

In [123]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [126]:
# create an array of size 3x3 filled with 6s of complex type
d = np.full((3, 3), 6, dtype = 'complex')

In [127]:
d

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [128]:
# 2x2 array with random values
e = np.random.random((2,2))

In [129]:
e

array([[0.81971726, 0.09511685],
       [0.99910517, 0.16166458]])

- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
   - **arange:** returns evenly spaced values within a given interval. **step** size is specified.
   - **linspace:** returns evenly spaced values within a given interval. **num** no. of elements are returned.

In [130]:
np.array(range(0,39,5))

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [131]:
# create a sequence of integers from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)

In [132]:
f

array([ 0,  5, 10, 15, 20, 25])

In [133]:
# create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)

In [135]:
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [136]:
# sequence of 10 random integers in range 0 to 10
h = np.random.randint(0, 10, 10)

In [137]:
h

array([0, 9, 0, 3, 6, 2, 5, 8, 6, 2])

- **Reshaping array:** We can use **reshape** method to reshape an array. Consider an array with shape (a1, a2, a3, ..., aN). We can reshape and convert it into another array with shape (b1, b2, b3, ....., bM). The only required condition is:   <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*a1 x a2 x a3 .... x aN = b1 x b2 x b3 .... x bM *. (i.e original size of array remains unchanged.)

In [146]:
# reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3, order='F')

In [147]:
newarr

array([[[1, 2, 0],
        [1, 3, 2]],

       [[5, 2, 4],
        [2, 4, 1]]])

- **Flatten array:** We can use **flatten** method to get a copy of array collapsed into **one dimension**. It accepts *order* argument. Default value is 'C' (for row-major order). Use 'F' for column major order.

In [140]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [141]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
flarr = arr.flatten('F')

In [145]:
flarr

array([1, 4, 2, 5, 3, 6])

## Array Indexing
---

Knowing the basics of array indexing is important for analysing and manipulating the array object.
NumPy offers many ways to do array indexing.

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [158]:
# an exemplar array
arr = np.array([[-1, 2, 0, 4,1],
                [4, -0.5, 6, 0,3],
                [2.6, 0, 7, 8, 4],
                [3, -7, 4, 2.0, 3],
                [3, -7, 4, 2.0, 3]])

In [159]:
arr

array([[-1. ,  2. ,  0. ,  4. ,  1. ],
       [ 4. , -0.5,  6. ,  0. ,  3. ],
       [ 2.6,  0. ,  7. ,  8. ,  4. ],
       [ 3. , -7. ,  4. ,  2. ,  3. ],
       [ 3. , -7. ,  4. ,  2. ,  3. ]])

In [160]:
arr.flatten()[::2]

array([-1. ,  0. ,  1. , -0.5,  0. ,  2.6,  7. ,  4. , -7. ,  2. ,  3. ,
        4. ,  3. ])

In [156]:
temp = arr[::2, -2:]

In [157]:
temp

array([[0., 4.],
       [7., 8.]])

- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

In [161]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]

In [162]:
temp

array([4., 6., 0., 3.])

In [163]:
r = [0,1,2,3]
c = [3,2,1,0]

In [165]:
arr[r,c]

array([4., 6., 0., 3.])

In [164]:
for x,y in zip(r,c):
    print(arr[x][y])

4.0
6.0
0.0
3.0


- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [166]:
arr

array([[-1. ,  2. ,  0. ,  4. ,  1. ],
       [ 4. , -0.5,  6. ,  0. ,  3. ],
       [ 2.6,  0. ,  7. ,  8. ,  4. ],
       [ 3. , -7. ,  4. ,  2. ,  3. ],
       [ 3. , -7. ,  4. ,  2. ,  3. ]])

In [167]:
1 > 0

True

In [168]:
arr > 0

array([[False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [169]:
cond = arr > 0

In [170]:
cond

array([[False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [171]:
# array elements which satisfy the condition
temp = arr[cond]

In [172]:
temp

array([2. , 4. , 1. , 4. , 6. , 3. , 2.6, 7. , 8. , 4. , 3. , 4. , 2. ,
       3. , 3. , 4. , 2. , 3. ])

## Basic operations
---

Plethora of built-in arithmetic functions are provided in NumPy.

- **Operations on single array:** We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

**Here are some examples:**

In [173]:
1+1

2

In [174]:
a = np.array([1, 2, 5, 3])

In [175]:
# add 1 to every element
a+1

array([2, 3, 6, 4])

In [176]:
# subtract 3 from each element
a-3

array([-2, -1,  2,  0])

In [177]:
# multiply each element by 10
a*10

array([10, 20, 50, 30])

In [178]:
# square each element
a**2

array([ 1,  4, 25,  9])

In [179]:
a

array([1, 2, 5, 3])

In [180]:
# modify existing array
a *= 2

In [181]:
a

array([ 2,  4, 10,  6])

In [182]:
# sample array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])

In [183]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [9, 6, 0]])

In [184]:
# transpose of array
a.T

array([[1, 3, 9],
       [2, 4, 6],
       [3, 5, 0]])


- **Unary operators:** Many unary operations are provided as a method of **ndarray** class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

**Here are some examples:**

In [185]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

In [186]:
# maximum element of array
arr.max()

9

In [187]:
# row-wise maximum elements
arr.max(axis=1)

array([6, 7, 9])

In [188]:
arr.max(axis=0)

array([4, 7, 9])

In [189]:
# column wise minimum elements
arr.min(axis=0)

array([1, 1, 2])

In [190]:
# sum of all array elements
arr.sum()

38

In [191]:
# sum of each row
arr.sum(axis=1)

array([12, 13, 13])

In [193]:
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [192]:
# cumulative sum along each row
arr.cumsum(axis=1)

array([[ 1,  6, 12],
       [ 4, 11, 13],
       [ 3,  4, 13]])

---
- **Binary operators:** These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, *, etc. In case of +=, -=, *= operators, the exsisting array is modified.

**Here are some examples:**

In [194]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[4, 3], 
              [2, 1]])

In [195]:
# sum of arrays
a + b

array([[5, 5],
       [5, 5]])

In [196]:
# multiply arrays (elementwise multiplication)
a*b

array([[4, 6],
       [6, 4]])

In [197]:
# matrix multiplication
a.dot(b)

array([[ 8,  5],
       [20, 13]])


- **Universal functions (ufunc):** NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

**Note:** All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [198]:
a = np.array([0, np.pi/2, np.pi])

In [199]:
a

array([0.        , 1.57079633, 3.14159265])

In [200]:
np.sin(a)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [201]:
np.exp(a)

array([ 1.        ,  4.81047738, 23.14069263])

In [202]:
np.sqrt(a)

array([0.        , 1.25331414, 1.77245385])

## Sorting array
There is a simple **np.sort** method for sorting NumPy arrays.
Let's explore it a bit.

In [209]:
a = np.array([[1, 4, 2],
              [3, 4, 6],
              [0, -1, 5],
              [1,2,3]])

In [206]:
# array elements in sorted order
np.sort(a, axis=None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [212]:
b = a.reshape(2,2,3)

In [207]:
# sort array row wise
np.sort(a, axis=1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [215]:
# specify sort algorithm
np.sort(a, axis = 0, kind = 'mergesort')

array([[ 0, -1,  2],
       [ 1,  2,  3],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [223]:
# example to show sorting of structured array
## set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', 'int64'), ('cgpa', float)]
## values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
## creating array
arr = np.array(values, dtype = dtypes)

In [224]:
arr

array([(b'Hrithik', 2009, 8.5), (b'Ajay', 2008, 8.7),
       (b'Pankaj', 2008, 7.9), (b'Aakash', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')])

In [222]:
# array sorted by name
np.sort(arr, order = 'name')

array([(b'Aakash', 2009, 9. ), (b'Ajay', 2008, 8.7),
       (b'Hrithik', 2009, 8.5), (b'Pankaj', 2008, 7.9)],
      dtype=[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')])

In [233]:
# array sorted by grauation year and then cgpa
np.sort(arr, order = ['grad_year', 'cgpa'])

TypeError: bad operand type for unary -: 'str'

# Stacking and Splitting

Several arrays can be stacked together along different axes.

- **np.vstack:** To stack arrays along vertical axis.

- **np.hstack:** To stack arrays along horizontal axis.

- **np.column_stack:** To stack 1-D arrays as columns into 2-D arrays.

- **np.concatenate:** To stack arrays along specified axis (axis is passed as argument).

In [234]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [235]:
# vertical stacking
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [236]:
# horizontal stacking
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [237]:
# new array
c = [5, 6]

In [238]:
# stacking array c as a column to array a
np.column_stack((a, c))

array([[1, 2, 5],
       [3, 4, 6]])

In [239]:
# stacking array c as a row to array a
np.row_stack((a, c))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [241]:
# concatenation method
np.concatenate((a,b), 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

For splitting, we have these fuctions:

- **np.hsplit:** Split array along horizontal axis.

- **np.vsplit:** Split array along vertical axis.

- **np.array_split:** Split array along specified axis.

In [242]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [243]:
# horizontal splitting in 2 parts
np.hsplit(a, 2)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [244]:
# vertical splitting in 2 parts
np.vsplit(a, 2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [246]:
np.split(a, 2, 1)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

# Broadcasting 

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.


Numpy operations are usually done element-by-element which requires two arrays to have exactly the same shape. Numpy's broadcasting rule relaxes this constraint when the arrays' shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation.

Consider the example given below:

In [247]:
a = np.array([1.0, 2.0, 3.0])

In [248]:
b = [2.0, 2.0, 2.0]

In [249]:
a*b

array([2., 4., 6.])

In [250]:
b = np.array([2.0])

In [251]:
a*b

array([2., 4., 6.])

![](http://scipy.github.io/old-wiki/pages/image0013830.gif?action=AttachFile&do=get&target=image001.gif)

**In above example, the scalar b is stretched to become an array of with the same shape as a so the shapes are compatible for element-by-element multiplication.**

We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as a. The new elements in b, as shown in above figure, are simply copies of the original scalar. Although, the stretching analogy is only conceptual. 
Numpy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible. Because Example 1 moves less memory, (b is a scalar, not an array) around during the multiplication, it is about 10% faster than Example 2 using the standard numpy on Windows 2000 with one million element arrays! 

## The Broadcasting Rule

In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or 
one of them must be **one**.

Let us see some examples:
```
A(2-D array): 4 x 3
B(1-D array):     3
Result      : 4 x 3
```

```
A(4-D array): 7 x 1 x 6 x 1
B(3-D array):     3 x 1 x 5
Result      : 7 x 3 x 6 x 5
```

But this would be a mismatch:
```
A: 4 x 3
B:     4
```
Now, let us see an example where both arrays get stretched.

In [252]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([0.0, 1.0, 2.0])

In [253]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [254]:
a[:, np.newaxis] + b

array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

![](http://scipy.github.io/old-wiki/pages/image004de9e.gif?action=AttachFile&do=get&target=image004.gif)
** In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays. **

# Working with datetime


Numpy has core array data types which natively support datetime functionality. The data type is called “datetime64”, so named because “datetime” is already taken by the datetime library included in Python.

Consider the example below for some examples:

In [255]:
# creating a date
today = np.datetime64('2017-12-31')

In [256]:
today

numpy.datetime64('2017-12-31')

In [259]:
# get year in numpy datetime object
np.datetime64(today, 'Y')

numpy.datetime64('2017')

In [262]:
# creating array of dates in a month
dates = np.arange('2017-12', '2018-01', dtype='datetime64[D]')

In [263]:
dates

array(['2017-12-01', '2017-12-02', '2017-12-03', '2017-12-04',
       '2017-12-05', '2017-12-06', '2017-12-07', '2017-12-08',
       '2017-12-09', '2017-12-10', '2017-12-11', '2017-12-12',
       '2017-12-13', '2017-12-14', '2017-12-15', '2017-12-16',
       '2017-12-17', '2017-12-18', '2017-12-19', '2017-12-20',
       '2017-12-21', '2017-12-22', '2017-12-23', '2017-12-24',
       '2017-12-25', '2017-12-26', '2017-12-27', '2017-12-28',
       '2017-12-29', '2017-12-30', '2017-12-31'], dtype='datetime64[D]')

In [264]:
today in dates

True

In [265]:
# arithmetic operation on dates
dur = np.datetime64('2018-05-22') - np.datetime64('2017-05-22')

In [266]:
dur

numpy.timedelta64(365,'D')

In [267]:
np.timedelta64(dur, 'W')

numpy.timedelta64(52,'W')

In [268]:
# sorting dates
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype='datetime64')

In [269]:
np.sort(a)

array(['2016-10-13', '2017-02-12', '2019-05-22'], dtype='datetime64[D]')

# Linear algebra in NumPy


The **Linear Algebra** module of NumPy offers various methods to apply linear algebra on any numpy array.

You can find:
- rank, determinant, trace, etc. of an array.
- eigen values of matrices
- matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
- solve linear or tensor equations
and much more!

Now, let us assume that we want to solve this linear equation set:
```
x + 2*y = 8
3*x + 4*y = 18
```
This problem can be solved using **linalg.solve** method as shown in example below:

In [270]:
# coefficients
a = np.array([[1, 2], [3, 4]])
# constants
b = np.array([8, 18])

np.linalg.solve(a, b)

array([2., 3.])

Consider the example below which explains how we can use numpy to do some matrix operations.

In [271]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [272]:
# rank of matrix
np.linalg.matrix_rank(A)

3

In [273]:
# trace of matrix
np.trace(A)

11

In [274]:
# determinant of matrix
np.linalg.det(A)

-306.0

In [275]:
# inverse of matrix
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [276]:
# matrix exponentiation
np.linalg.matrix_power(A, 3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

## Saving and loading numpy arrays


The ``.npy`` format is the standard binary file format in NumPy for
persisting a **single** arbitrary NumPy array on disk. The format stores all
of the shape and dtype information necessary to reconstruct the array
correctly even on another machine with a different architecture.
The format is designed to be as simple as possible while achieving
its limited goals.

The ``.npz`` format is the standard format for persisting **multiple** NumPy
arrays on disk. A ``.npz`` file is a zip file containing multiple ``.npy``
files, one for each array.

- **np.save(filename, array)** : saves a single array in ``npy`` format.

- **np.savez(filename, array_1[, array_2])** : saves multiple numpy arrays in ``npz`` format.

- **np.load(filename)** : load a ``npy`` or ``npz`` format file.

In [277]:
a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[6,5,4],
              [3,2,1]])

In [278]:
np.save("a.npy", a)

In [279]:
arr = np.load("a.npy")

In [280]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [281]:
np.savez("ab.npz", A=a, B=b)

In [282]:
X = np.load("ab.npz")

In [284]:
X['A']

array([[1, 2, 3],
       [4, 5, 6]])

In [285]:
X['B']

array([[6, 5, 4],
       [3, 2, 1]])

References:
- [broadcasting](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)
- [datetime in numpy](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#arrays-dtypes-dateunits)
- [linaer algebra in numpy](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

![](https://i.pinimg.com/736x/c8/90/b2/c890b24d364d6ae6413c37b70e6640ae--math-jokes-math-humor.jpg)